### ISSUE TITLE
Cannot find module 'twitch-webhook'

### ISSUE THREAD

**Issue by BethaNeeks** [true-dubach/node-twitch-webhook#5]
According to runnit and from using in my app, there's no index.js file, thus can't be required just by using;

`require('twitch-webhook')`

We need to use;

`require('twitch-webhook/src/index.js')`

Node Version: 8.9.3 and 9.3.0
NPM Version: 5.6.0

**Comment by k-egor-smirnov** [comment]
Thank you for response!  :thumbsup: 
Fixed in https://github.com/true-dubach/node-twitch-webhook/pull/6
