### ISSUE TITLE
Stream event doesn't work

### ISSUE THREAD

**Issue by k-egor-smirnov** [true-dubach/node-twitch-webhook#8]
# Why
It happens because Twitch replaced JSON property "topic" with HTTP header "Link" in some events and will do it with all the others. Also it's a [W3C standard](https://www.w3.org/TR/websub/)
# How to fix
Implement routing for events, for example 
`api.your-website.com/twitch-webhooks/follows`
`api.your-website.com/twitch-webhooks/streams`

**Comment by DaniilShev** [comment]
Fixed in #9 :)
